# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['ansible_runner',
 'ansible_runner.callbacks',
 'ansible_runner.display_callback',
 'ansible_runner.plugins']

package_data = \
{'': ['*']}

install_requires = \
['pexpect==4.6', 'psutil', 'python-daemon', 'pyyaml', 'six']

entry_points = \
{'console_scripts': ['ansible-runner = ansible_runner.__main__:main'],
 'receptor.worker': ['ansible_runner = ansible_runner.receptor_plugin']}

setup_kwargs = {
    'name': 'ansible-runner',
    'version': '1.4.6',
    'description': 'Consistent Ansible Pythin API and CLI with container and process isoluation runtime capabilities',
    'long_description': "Ansible Runner\n==============\n\n[![Documentation](https://readthedocs.org/projects/ansible-runner/badge/?version=stable)](https://ansible-runner.readthedocs.io/en/latest/)\n[![Code of Conduct](https://img.shields.io/badge/Code%20of%20Conduct-Ansible-silver.svg)](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html)\n[![Ansible Mailing lists](https://img.shields.io/badge/Mailing%20lists-Ansible-orange.svg)](https://docs.ansible.com/ansible/latest/community/communication.html#mailing-list-information)\n\n\n\nAnsible Runner is a tool and python library that helps when interfacing with Ansible directly or as part of another system whether that be through a container image interface, as a standalone tool, or as a Python module that can be imported. The goal is to provide a stable and consistent interface abstraction to Ansible.\n\nFor the latest documentation see: [https://ansible-runner.readthedocs.io](https://ansible-runner.readthedocs.io/en/latest/)\n\nGet Involved\n============\n\n* We use [GitHub issues](https://github.com/ansible/ansible-runner/issues) to track bug report and feature ideas...\n* ... and [GitHub Milestones](https://github.com/ansible/ansible-runner/milestones) to track what's for the next release\n* Want to contribute, check out our [guide](CONTRIBUTING.md)\n* Join us in the `#ansible-runner` channel on Freenode IRC\n* Join the discussion in [awx-project](https://groups.google.com/forum/#!forum/awx-project)\n* For the full list of Ansible email Lists, IRC channels see the [Ansible Mailing lists](https://docs.ansible.com/ansible/latest/community/communication.html#mailing-list-information)\n",
    'author': 'Red Hat Ansible',
    'author_email': None,
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/ansible/ansible-runner',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*',
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
